<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends EntityRepository
{
    public function findMarquesByOrderTitle($form = false) {
        $query = $this->createQueryBuilder('m')
            ->orderBy('m.title');

        if ($form) {
            return $query;
        }

        return $query->getQuery()->getResult();

    }
}
