services:
#    troiswa_back.example:
#        class: Troiswa\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    troiswa_back.monsuperservice:
        class: Troiswa\BackBundle\Util\Utility
