<?php

namespace Troiswa\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Retourne les commentaires d'un produit
     * @author Eric
     *
     * @param $idProduct
     * @return array
     */
    public function findCommentsByProductId($idProduct, $form = false){

        $query = $this->createQueryBuilder('com')
            ->select('com, client')
            ->leftJoin('com.client', 'client')
            ->leftJoin('com.product', 'prod')
            ->where('prod.id = :idProduct')
            ->orderBy('com.created', 'DESC')
            ->setParameter('idProduct', $idProduct);

        if ($form)
        {
            return $query;
        }

        return $query->getQuery()->getResult();
    }
}
