<?php

namespace Troiswa\BackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends EntityRepository
{
    
    /**
     * Retourne la liste des marque par ordre alphabétique
     * @author Eric
     * @param type $form
     * @return mixed
     */
    public function findAllBrandOrderByTitle($form = false) {
        
        $query = $this->createQueryBuilder('brand')
            ->orderBy('brand.title');

        if ($form) {
            return $query;
        }

        return $query->getQuery()->getResult();
    }
    
    /**
     * Retourne la marque avec son logo
     * @author Eric
     * @param array $dataUrl
     * @return mixed
     */
    public function findOneBrandWithLogoById($dataUrl) {

        $query = $this->createQueryBuilder('brand')
                ->select('brand, logo')
                ->leftJoin('brand.logo', 'logo')
                ->where('brand.id = :id')
                ->setParameter('id', $dataUrl['id']);
        
        return $query->getQuery()->getSingleResult();
    }
}
