services:
#    troiswa_front.example:
#        class: Troiswa\FrontBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    troiswa_front.cart:
        class: Troiswa\FrontBundle\Util\Cart
        arguments: ["@session", "@doctrine.orm.entity_manager"]